### ISSUE TITLE
Not able to run the code

### ISSUE THREAD

**Issue by Vector-9974** [alejandro-ao/ask-multiple-pdfs#2]
(gitenvt) C:\Users\Work\Desktop\dataProcess\ask-multiple-pdfs>streamlit run app.py
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Work\Desktop\dataProcess\gitenvt\Scripts\streamlit.exe\__main__.py", line 4, in <module>
  File "C:\Users\Work\Desktop\dataProcess\gitenvt\Lib\site-packages\streamlit\__init__.py", line 55, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "C:\Users\Work\Desktop\dataProcess\gitenvt\Lib\site-packages\streamlit\delta_generator.py", line 43, in <module>
    from streamlit.elements.arrow_altair import ArrowAltairMixin
  File "C:\Users\Work\Desktop\dataProcess\gitenvt\Lib\site-packages\streamlit\elements\arrow_altair.py", line 36, in <module>
    from altair.vegalite.v4.api import Chart
ModuleNotFoundError: No module named 'altair.vegalite.v4'

This is the error that is coming when running the streamlit run app.py

How to rectify it

**Comment by dogg223405** [comment]
I am assuming you are using Win. Search in Explorer the PythonXX/Scripts folder where you have app.py. and add streamlit with the full path in the System Variables.

**Comment by DrJulioCid** [comment]
Same problem with Delta generator and altair.vegalite 
Did you solve it?

**Comment by DrJulioCid** [comment]
Im on Mac BTW

**Comment by justin-parker** [comment]
from your shell run:
`pip install altair==4.2.2`

[source post talking about this bug/fix](https://discuss.huggingface.co/t/streamlit-spaces-with-modulenotfounderror-no-module-named-altair-vegalite-v4-error/39683)

**Comment by Daniel-Trung-Nguyen** [comment]
installing altair fixed the issue for me. But I ran into this error when processing a document
`ImportError: Could not import tiktoken python package. This is needed in order to for OpenAIEmbeddings. Please install it with pip install tiktoken`.

![image](https://github.com/alejandro-ao/ask-multiple-pdfs/assets/22897462/c8af7672-b186-4257-9a69-18d8a68bca62)

**Comment by rhoconlinux** [comment]
Hi there, 
Cannot get it work on macos. 

`(python394) ╭─rho@MacBook-Pro.local ~/Library/CloudStorage/Dropbox/ask-multiple-pdfs-main  
╰─➤  streamlit run app.py                           
Traceback (most recent call last):
  File "/Users/rho/.pyenv/versions/3.9.2/bin/streamlit", line 5, in <module>
    from streamlit.web.cli import main
  File "/Users/rho/.pyenv/versions/3.9.2/lib/python3.9/site-packages/streamlit/__init__.py", line 55, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/Users/rho/.pyenv/versions/3.9.2/lib/python3.9/site-packages/streamlit/delta_generator.py", line 43, in <module>
    from streamlit.elements.arrow_altair import ArrowAltairMixin
  File "/Users/rho/.pyenv/versions/3.9.2/lib/python3.9/site-packages/streamlit/elements/arrow_altair.py", line 36, in <module>
    from altair.vegalite.v4.api import Chart
ModuleNotFoundError: No module named 'altair.vegalite.v4'`

I tryied 4.0.0 4.1 4.2 and 4.2.2 of altair and 1.18.1 and 1.22.1 of streamlit. 
Allways returns the same thing. 
Thanks in advance for the help.

**Comment by prudhvi2934** [comment]
add 'altair==4.2.2' in requirements.txt and pip install -r requirements.txt. It worked for me, I'm using macOS.
